{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prettydoc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prettydoc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prettydoc/prettydoc_{{ version }}.tar.gz
  sha256: 1094a69b026238d149435472b4f41c75151c7370a1be6c6332147c88ad4c4829

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rmarkdown >=1.0
  run:
    - r-base
    - r-rmarkdown >=1.0

test:
  commands:
    - $R -e "library('prettydoc')"           # [not win]
    - "\"%R%\" -e \"library('prettydoc')\""  # [win]

about:
  home: https://github.com/yixuan/prettydoc
  license: Apache-2.0
  summary: Creating tiny yet beautiful documents and vignettes from R Markdown. The package provides the 'html_pretty' output format as an alternative to the 'html_document' and 'html_vignette' engines that convert R Markdown into HTML pages. Various themes and syntax highlight styles are supported.
  license_family: APACHE
  license_file: LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: prettydoc
# Type: Package
# Title: Creating Pretty Documents from R Markdown
# Version: 0.3.0
# Date: 2019-07-15
# Authors@R: c( person("Yixuan", "Qiu", , "yixuan.qiu@cos.name", c("aut", "cre")), person("Jason", "Long", , "jlong@github.com", "ctb", comment = "the Cayman, Tactile and Architect themes"), person("Renyuan", "Zou", , "zourenyuan@gmail.com", "ctb", comment = "the Leonids theme"), person("Michael", "Rose", role = "ctb", comment = "the HPSTR theme"), person("JJ", "Allaire", , "jj.allaire@gmail.com", "ctb", comment = "pandoc template for rmarkdown"), person("Hadley", "Wickham", , "h.wickham@gmail.com", "ctb", comment = "the html_vignette() function"), person("Yihui", "Xie", , "xie@yihui.name", "ctb", comment = "the html_vignette() function"), person("Steve", "Matteson", role = "ctb", comment = "the Open Sans fonts"), person("Emily", "Eisenberg", role = "ctb", comment = "the KaTeX library"), person("Sophie", "Alpert", role = "ctb", comment = "the KaTeX library") )
# Description: Creating tiny yet beautiful documents and vignettes from R Markdown. The package provides the 'html_pretty' output format as an alternative to the 'html_document' and 'html_vignette' engines that convert R Markdown into HTML pages. Various themes and syntax highlight styles are supported.
# Imports: rmarkdown (>= 1.0)
# Suggests: knitr, KernSmooth
# SystemRequirements: pandoc (>= 1.12.3)
# VignetteBuilder: knitr, rmarkdown
# URL: https://github.com/yixuan/prettydoc
# BugReports: https://github.com/yixuan/prettydoc/issues
# License: Apache License (>= 2.0)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-16 17:42:04 UTC; qyx
# Author: Yixuan Qiu [aut, cre], Jason Long [ctb] (the Cayman, Tactile and Architect themes), Renyuan Zou [ctb] (the Leonids theme), Michael Rose [ctb] (the HPSTR theme), JJ Allaire [ctb] (pandoc template for rmarkdown), Hadley Wickham [ctb] (the html_vignette() function), Yihui Xie [ctb] (the html_vignette() function), Steve Matteson [ctb] (the Open Sans fonts), Emily Eisenberg [ctb] (the KaTeX library), Sophie Alpert [ctb] (the KaTeX library)
# Maintainer: Yixuan Qiu <yixuan.qiu@cos.name>
# Repository: CRAN
# Date/Publication: 2019-07-18 06:36:17 UTC
