travis:
  secure:
    BINSTAR_TOKEN: A4EpKG81mBWi9rAtbSBaG+CAVFyACRptQZ9yG5gi/mX2/g+3WRJ5opG845vkuxeb4O8iMqy8Dw0s8fXliow3f8bwjk3euQDteIRsgyawzfjcbzi6ADVDKKM4cTHPRTYXmlDjoqLAgvQZKlYp8n5Lhq//uXQ8iGsfhrQ5HAN1v8QEQnVxV6RKuc3YzXYoOeB9p5p/yuT7ZE3JvYwQfLcChyx4VRW3SaOIJ1kFdheq0rZLsDzX1dSUGXxQVUiWjXzYoyD0JNua/3456CvkTQL5eNh3IRo/AO39EfzNldLU9cMHUheL4WElqSaT2hX08zW4VaE95V7RAROFrp/eaKO+hoPHpyLpMNb2ReD47Uh6KKycnhZ6nJN7IdiSjpET1BwOJ5n2pEOkiwYnrImjlLkg2I5jHECS89lyvN6JNqKWMUEbYoD77Ewe2QdeUZsxIB8xqfIivWsuCsvoH19R1klHOOCu4XBjwxEMr8NsaxBvJU0ZN5p8mbCjAgIaztdWkLYGtndLfZEoukbxCeFzIZanup+Zb3kNHoVvaxWmicshi3Zt//6nGkhgUP5I5s6kv7HFqBGu4JPE2TUJfqax12PQgwyQFLP37ueSNAX3727P2m0gTAESXR6mt3QNJvfQxZHkLLb+rju2KIMoLnzDx623WzfleEgizgc8yqztXC0WYqk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
