travis:
  secure:
    BINSTAR_TOKEN: RvFqsmY8hDFeeNx5KbAXZiMkYvoakBXPqAG0/q6fAKbdU+J22q+SaY/8+qOw7BlIYCGvtQRfqQa7tTDBFRye+7RYupZDCEo+O4TDZzzTp+5Qz8l4tyqW5+uo07W1wWIDGvqq8CSrGW1n0FNeNXMP3s3fU3F+ddPyfV47LZW/1bHOj5jnjYhA35YAGu1GaOqd3NJqo+E3IXYFetN/g1f/nVkikMtHcn2u8lnwwb2lpuMGREJSFLPtEGNDTZMua0nAsxgpdn8rleMDJtlMxh2rbV9flcdmJEejYVJSkSZr2/exyI5xeihVlJarhfVKsuVtpQKBQ5FveOcPJ69Cmlw12j7EkH9cKcpw1R8HUPluMaYmABJA1tLC+E6WUzt0+kBgyaz+vzDoVn1lyv6Dja5AaWwz3bJffBmKhhuNgAIH1oLKjhoswPjvGGa09RCm9z044R+6kynPZxr5bi4LvZMI6OqL0oY9YAX79G3ioSi7UeRHrFjvrwyhuy96gm16TQFZcz67Gec/jl08HLnvfZdOn+mTWc7AajWIxsjY8vq1XKX/uP95nWZUDzBfacWbBnJCGrS/jh2Ea6KoKYpyaEtlFN/fD2UKFXCCPew7fjlw5BHlL0nOGqKbqeYY8Z5swx6MQbqfe2OzxUX/zhwWja74E11bl1UQQcRx30fO326tsBU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
