travis:
  secure:
    BINSTAR_TOKEN: TT/9K19oDJwah7B3xqoRmbSOLfJOqxz7PKmcmBxc26cNZLowtVjuPfyUfHKWdxo32kKW+s4gdQnGGFVlGJ/pff+kVZSUVzHFQO8RwYz2GyJFCGtgurulVaehrAueU+4FqJBWhiHxG1demVusyrOIby25DZQqjTDbeWOkx6hX7CiLt5kmWAruAfMw/896Bm4dWOCFgbweJt8LRBDr92v0GaoOeTQkoaObXGGFvWnzvI49uDRDgyOPAnuu62VYihLUVAt3cqzAZWoiUI8teN40SFsewRtVkRQSBXEET22Q6Zkwww6P0/l46S7iEj5SH8dW59QKeed80CTZrA6ESqx6EFPW71ptpGIFcyKtgnR0+ZsRXIQO0ePUH2H8LTIBanrIc9jStr8c5de8ePsOGJEUODEe5GdicbhYL7NfarZewL3AxsL0Soi2UvCshkqWhAWLW5FZChWA9UIdxRfFV2y9CGkIBe148wH61HIE2RqHhy3Ehy94sSGA88rkyQqq/Mj0g7L+aZL6S7t06ep66Hm1Y4MBGKG+LaWDGTDCD6E1iCmB6sOO+W1H1m8MHw4YhvgrX+xGCudYTwzdbFG51ZzN9D16+WkSgeykZHriHK6X4GXkrQfsNIKirNmo17qmpD+d7IR2eDUOFICgE+OVG/KRl13VNLYFXYRSBd0rI3I4Ozc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
