appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FLFGYnOPOOS7HzOFh0UOjp2bkU8UqmzRTw7aPDOY74V1j3ZMADOxJLbRxISf30+HqQpyeq23pOPvrtK+KXVGXv1GQz68N5KVLPBJaCxriNA5GKB9kz+rEIlQyu6yhLAIyNjbG5StGZr8XslzxVIq4aK76y4ncITq1yNyoqGA6uMxRwcULc3ixzUf/MFFRRn2u0mQM+YQJBtY7FF1rJdPBVr3OFoBUoi9JBZQCd6Iz1oD1VVXYJl67sBaB9semqUZn4ZZjjA/P/3oWTmQ5Sv2kA8GxYhNQvxnBF2DfOyIXaA4gzn92+bKHejDaoWjdiYKBToPDNLzzUqwc3sfvDowdR6Ox2VDj18fRRFywUSCCtac5HwwYCECTbziQ7ASCP4BX/SiIjLW8rpKYljuCd42PVO0d9MV62BV9r+RvEu0iycp1WXSbJEU4jeA0eVocHginozDZeAsDYnWwz99Puk/4vTsOYRa7sRbkxIxWfvovVHsdV2VxShbOBEW00itzQim/r89bS2UmzMpqvPmfeZ8qonH/CshTAe4YMD/3+ruj5wAUZCWAKKqNORFKSMGb+l42L/tGJT9xOHh2MU8vIiWXnsb31t7PJAefn9ftvGPzmG9n9AnefzoPWrBPF7BxOQq9RHSWFavaM8LA39lbbxMzKlQWIwiFbxGlziQC887A8A=}
